version: '3.8'

services:
  db:
    container_name: mongodb
    image: dockerslayer10/mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data/sample_posts.json:/data/sample_posts.json
    command: >
      bash -c "
      mongod --bind_ip_all &
      sleep 5 &&
      mongoimport --drop --db wanderlust --collection posts --file /data/sample_posts.json --jsonArray &&
      wait
      "
    networks:
      - wanderlust

  backend:
    container_name: backend
    image: dockerslayer10/wanderlust-backend-git:latest
    depends_on:
      - db
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/wanderlust
      - CORS_ORIGIN=http://192.168.56.50:5173
      - FRONTEND_URL=http://192.168.56.50:5173
    ports:
      - "5000:5000"
    networks:
      - wanderlust

  frontend:
    container_name: frontend
    image: dockerslayer10/wanderlust-frontend-git:latest
    environment:
      - VITE_API_PATH=http://192.168.56.50:5000
    ports:
      - "5173:5173"
    networks:
      - wanderlust

networks:
  wanderlust:
    name: wanderlust
    driver: bridge
    